jobs:
  main:
    name: Check
    runs-on: ubuntu-20.04

    steps:
      - name: Begin
        uses: actions/checkout@v2
      - name: Fetch Packages
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Unit Tests
        run: ./check/main

name: Main

on:
  schedule:
    - cron: "45 1/3 * * *"
